apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythontest
  labels:
    app: pythontest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythontest
  template:
    metadata:
      labels:
        app: pythontest
    spec:
      containers:
        - name: pythontest
          image: localhost:5000/flask_hello:latest
          ports:
            - containerPort: 5000
